version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bazaquestion-postgres
    environment:
      POSTGRES_DB: bazaquestion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bazaquestion-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bazaquestion-network:
    driver: bridge 